name: ETL Pipeline

on:
  push:
    branches:
    - main
  
jobs:
  etl-pipeline:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setting up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Libraries Installations
      run: pip install pandas requests datetime

    - name: Run the script
      run: python app.py

    - name: Push new files back to master.
      uses: mikeal/publish-to-github-action@1.0.0
  
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH_NAME: 'main'




